// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Kup_LxU8RAgjsNNmmf4rOsU2FByxUgY',
    appId: '1:158289361374:web:e89743a607b6205c02854f',
    messagingSenderId: '158289361374',
    projectId: 'dev-malatanglog',
    authDomain: 'dev-malatanglog.firebaseapp.com',
    storageBucket: 'dev-malatanglog.firebasestorage.app',
    measurementId: 'G-86QDRVGRZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XqnsywRZfT7wZGD__0tsl_V9w9tR5i4',
    appId: '1:158289361374:android:4dff601f785cd76502854f',
    messagingSenderId: '158289361374',
    projectId: 'dev-malatanglog',
    storageBucket: 'dev-malatanglog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgr4GX-CYqeSersVH-HZEuSGLdO2LT08M',
    appId: '1:158289361374:ios:8f4cc29eece7f4d102854f',
    messagingSenderId: '158289361374',
    projectId: 'dev-malatanglog',
    storageBucket: 'dev-malatanglog.firebasestorage.app',
    iosClientId: '158289361374-g05j87b0lrilr83b9n9cokl3vdasq3ij.apps.googleusercontent.com',
    iosBundleId: 'com.viuts.malatanglog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgr4GX-CYqeSersVH-HZEuSGLdO2LT08M',
    appId: '1:158289361374:ios:8f4cc29eece7f4d102854f',
    messagingSenderId: '158289361374',
    projectId: 'dev-malatanglog',
    storageBucket: 'dev-malatanglog.firebasestorage.app',
    iosClientId: '158289361374-g05j87b0lrilr83b9n9cokl3vdasq3ij.apps.googleusercontent.com',
    iosBundleId: 'com.viuts.malatanglog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Kup_LxU8RAgjsNNmmf4rOsU2FByxUgY',
    appId: '1:158289361374:web:cb325d11c16b718f02854f',
    messagingSenderId: '158289361374',
    projectId: 'dev-malatanglog',
    authDomain: 'dev-malatanglog.firebaseapp.com',
    storageBucket: 'dev-malatanglog.firebasestorage.app',
    measurementId: 'G-K3PCDF51P4',
  );
}
