// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: malatanglog/v1/malatanglog.proto

package malatanglogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FlavorService_GetShops_FullMethodName     = "/malatanglog.v1.FlavorService/GetShops"
	FlavorService_CreateReview_FullMethodName = "/malatanglog.v1.FlavorService/CreateReview"
	FlavorService_UpdateReview_FullMethodName = "/malatanglog.v1.FlavorService/UpdateReview"
	FlavorService_DeleteReview_FullMethodName = "/malatanglog.v1.FlavorService/DeleteReview"
	FlavorService_ListReviews_FullMethodName  = "/malatanglog.v1.FlavorService/ListReviews"
)

// FlavorServiceClient is the client API for FlavorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlavorServiceClient interface {
	// Get shops (searchable by query)
	GetShops(ctx context.Context, in *GetShopsRequest, opts ...grpc.CallOption) (*GetShopsResponse, error)
	// Create a new Review
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*Review, error)
	// Update an existing Review
	UpdateReview(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*Review, error)
	// Delete a Review
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*Review, error)
	// List user's Reviews
	ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsResponse, error)
}

type flavorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlavorServiceClient(cc grpc.ClientConnInterface) FlavorServiceClient {
	return &flavorServiceClient{cc}
}

func (c *flavorServiceClient) GetShops(ctx context.Context, in *GetShopsRequest, opts ...grpc.CallOption) (*GetShopsResponse, error) {
	out := new(GetShopsResponse)
	err := c.cc.Invoke(ctx, FlavorService_GetShops_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, FlavorService_CreateReview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) UpdateReview(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, FlavorService_UpdateReview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*Review, error) {
	out := new(Review)
	err := c.cc.Invoke(ctx, FlavorService_DeleteReview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flavorServiceClient) ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsResponse, error) {
	out := new(ListReviewsResponse)
	err := c.cc.Invoke(ctx, FlavorService_ListReviews_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlavorServiceServer is the server API for FlavorService service.
// All implementations must embed UnimplementedFlavorServiceServer
// for forward compatibility
type FlavorServiceServer interface {
	// Get shops (searchable by query)
	GetShops(context.Context, *GetShopsRequest) (*GetShopsResponse, error)
	// Create a new Review
	CreateReview(context.Context, *CreateReviewRequest) (*Review, error)
	// Update an existing Review
	UpdateReview(context.Context, *UpdateReviewRequest) (*Review, error)
	// Delete a Review
	DeleteReview(context.Context, *DeleteReviewRequest) (*Review, error)
	// List user's Reviews
	ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsResponse, error)
	mustEmbedUnimplementedFlavorServiceServer()
}

// UnimplementedFlavorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlavorServiceServer struct {
}

func (UnimplementedFlavorServiceServer) GetShops(context.Context, *GetShopsRequest) (*GetShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShops not implemented")
}
func (UnimplementedFlavorServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedFlavorServiceServer) UpdateReview(context.Context, *UpdateReviewRequest) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReview not implemented")
}
func (UnimplementedFlavorServiceServer) DeleteReview(context.Context, *DeleteReviewRequest) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedFlavorServiceServer) ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReviews not implemented")
}
func (UnimplementedFlavorServiceServer) mustEmbedUnimplementedFlavorServiceServer() {}

// UnsafeFlavorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlavorServiceServer will
// result in compilation errors.
type UnsafeFlavorServiceServer interface {
	mustEmbedUnimplementedFlavorServiceServer()
}

func RegisterFlavorServiceServer(s grpc.ServiceRegistrar, srv FlavorServiceServer) {
	s.RegisterService(&FlavorService_ServiceDesc, srv)
}

func _FlavorService_GetShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).GetShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_GetShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).GetShops(ctx, req.(*GetShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_UpdateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).UpdateReview(ctx, req.(*UpdateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlavorService_ListReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlavorServiceServer).ListReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlavorService_ListReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlavorServiceServer).ListReviews(ctx, req.(*ListReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlavorService_ServiceDesc is the grpc.ServiceDesc for FlavorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlavorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "malatanglog.v1.FlavorService",
	HandlerType: (*FlavorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShops",
			Handler:    _FlavorService_GetShops_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _FlavorService_CreateReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _FlavorService_UpdateReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _FlavorService_DeleteReview_Handler,
		},
		{
			MethodName: "ListReviews",
			Handler:    _FlavorService_ListReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "malatanglog/v1/malatanglog.proto",
}
