// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/viuts/malatanglog/apps/backend/internal/domain"
)

func newShop(db *gorm.DB, opts ...gen.DOOption) shop {
	_shop := shop{}

	_shop.shopDo.UseDB(db, opts...)
	_shop.shopDo.UseModel(&domain.Shop{})

	tableName := _shop.shopDo.TableName()
	_shop.ALL = field.NewAsterisk(tableName)
	_shop.ID = field.NewField(tableName, "id")
	_shop.Name = field.NewString(tableName, "name")
	_shop.Category = field.NewString(tableName, "category")
	_shop.Lat = field.NewFloat64(tableName, "lat")
	_shop.Lng = field.NewFloat64(tableName, "lng")
	_shop.IsChain = field.NewBool(tableName, "is_chain")
	_shop.SourceID = field.NewString(tableName, "source_id")
	_shop.Geom = field.NewString(tableName, "geom")
	_shop.Address = field.NewString(tableName, "address")
	_shop.Phone = field.NewString(tableName, "phone")
	_shop.OpeningHours = field.NewString(tableName, "opening_hours")
	_shop.ImageURLs = field.NewField(tableName, "image_urls")
	_shop.Rating = field.NewFloat64(tableName, "rating")
	_shop.SourceURL = field.NewString(tableName, "source_url")
	_shop.ClearanceRadius = field.NewFloat64(tableName, "clearance_radius")
	_shop.CreatedAt = field.NewTime(tableName, "created_at")
	_shop.UpdatedAt = field.NewTime(tableName, "updated_at")

	_shop.fillFieldMap()

	return _shop
}

type shop struct {
	shopDo

	ALL             field.Asterisk
	ID              field.Field
	Name            field.String
	Category        field.String
	Lat             field.Float64
	Lng             field.Float64
	IsChain         field.Bool
	SourceID        field.String
	Geom            field.String
	Address         field.String
	Phone           field.String
	OpeningHours    field.String
	ImageURLs       field.Field
	Rating          field.Float64
	SourceURL       field.String
	ClearanceRadius field.Float64
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (s shop) Table(newTableName string) *shop {
	s.shopDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shop) As(alias string) *shop {
	s.shopDo.DO = *(s.shopDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shop) updateTableName(table string) *shop {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.Name = field.NewString(table, "name")
	s.Category = field.NewString(table, "category")
	s.Lat = field.NewFloat64(table, "lat")
	s.Lng = field.NewFloat64(table, "lng")
	s.IsChain = field.NewBool(table, "is_chain")
	s.SourceID = field.NewString(table, "source_id")
	s.Geom = field.NewString(table, "geom")
	s.Address = field.NewString(table, "address")
	s.Phone = field.NewString(table, "phone")
	s.OpeningHours = field.NewString(table, "opening_hours")
	s.ImageURLs = field.NewField(table, "image_urls")
	s.Rating = field.NewFloat64(table, "rating")
	s.SourceURL = field.NewString(table, "source_url")
	s.ClearanceRadius = field.NewFloat64(table, "clearance_radius")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *shop) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shop) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["category"] = s.Category
	s.fieldMap["lat"] = s.Lat
	s.fieldMap["lng"] = s.Lng
	s.fieldMap["is_chain"] = s.IsChain
	s.fieldMap["source_id"] = s.SourceID
	s.fieldMap["geom"] = s.Geom
	s.fieldMap["address"] = s.Address
	s.fieldMap["phone"] = s.Phone
	s.fieldMap["opening_hours"] = s.OpeningHours
	s.fieldMap["image_urls"] = s.ImageURLs
	s.fieldMap["rating"] = s.Rating
	s.fieldMap["source_url"] = s.SourceURL
	s.fieldMap["clearance_radius"] = s.ClearanceRadius
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s shop) clone(db *gorm.DB) shop {
	s.shopDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shop) replaceDB(db *gorm.DB) shop {
	s.shopDo.ReplaceDB(db)
	return s
}

type shopDo struct{ gen.DO }

type IShopDo interface {
	gen.SubQuery
	Debug() IShopDo
	WithContext(ctx context.Context) IShopDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IShopDo
	WriteDB() IShopDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IShopDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IShopDo
	Not(conds ...gen.Condition) IShopDo
	Or(conds ...gen.Condition) IShopDo
	Select(conds ...field.Expr) IShopDo
	Where(conds ...gen.Condition) IShopDo
	Order(conds ...field.Expr) IShopDo
	Distinct(cols ...field.Expr) IShopDo
	Omit(cols ...field.Expr) IShopDo
	Join(table schema.Tabler, on ...field.Expr) IShopDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IShopDo
	RightJoin(table schema.Tabler, on ...field.Expr) IShopDo
	Group(cols ...field.Expr) IShopDo
	Having(conds ...gen.Condition) IShopDo
	Limit(limit int) IShopDo
	Offset(offset int) IShopDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IShopDo
	Unscoped() IShopDo
	Create(values ...*domain.Shop) error
	CreateInBatches(values []*domain.Shop, batchSize int) error
	Save(values ...*domain.Shop) error
	First() (*domain.Shop, error)
	Take() (*domain.Shop, error)
	Last() (*domain.Shop, error)
	Find() ([]*domain.Shop, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Shop, err error)
	FindInBatches(result *[]*domain.Shop, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.Shop) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IShopDo
	Assign(attrs ...field.AssignExpr) IShopDo
	Joins(fields ...field.RelationField) IShopDo
	Preload(fields ...field.RelationField) IShopDo
	FirstOrInit() (*domain.Shop, error)
	FirstOrCreate() (*domain.Shop, error)
	FindByPage(offset int, limit int) (result []*domain.Shop, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IShopDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s shopDo) Debug() IShopDo {
	return s.withDO(s.DO.Debug())
}

func (s shopDo) WithContext(ctx context.Context) IShopDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shopDo) ReadDB() IShopDo {
	return s.Clauses(dbresolver.Read)
}

func (s shopDo) WriteDB() IShopDo {
	return s.Clauses(dbresolver.Write)
}

func (s shopDo) Session(config *gorm.Session) IShopDo {
	return s.withDO(s.DO.Session(config))
}

func (s shopDo) Clauses(conds ...clause.Expression) IShopDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shopDo) Returning(value interface{}, columns ...string) IShopDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shopDo) Not(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shopDo) Or(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shopDo) Select(conds ...field.Expr) IShopDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shopDo) Where(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shopDo) Order(conds ...field.Expr) IShopDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shopDo) Distinct(cols ...field.Expr) IShopDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shopDo) Omit(cols ...field.Expr) IShopDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shopDo) Join(table schema.Tabler, on ...field.Expr) IShopDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shopDo) LeftJoin(table schema.Tabler, on ...field.Expr) IShopDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shopDo) RightJoin(table schema.Tabler, on ...field.Expr) IShopDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shopDo) Group(cols ...field.Expr) IShopDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shopDo) Having(conds ...gen.Condition) IShopDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shopDo) Limit(limit int) IShopDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shopDo) Offset(offset int) IShopDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shopDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IShopDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shopDo) Unscoped() IShopDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shopDo) Create(values ...*domain.Shop) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shopDo) CreateInBatches(values []*domain.Shop, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shopDo) Save(values ...*domain.Shop) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shopDo) First() (*domain.Shop, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Shop), nil
	}
}

func (s shopDo) Take() (*domain.Shop, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Shop), nil
	}
}

func (s shopDo) Last() (*domain.Shop, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Shop), nil
	}
}

func (s shopDo) Find() ([]*domain.Shop, error) {
	result, err := s.DO.Find()
	return result.([]*domain.Shop), err
}

func (s shopDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.Shop, err error) {
	buf := make([]*domain.Shop, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shopDo) FindInBatches(result *[]*domain.Shop, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shopDo) Attrs(attrs ...field.AssignExpr) IShopDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shopDo) Assign(attrs ...field.AssignExpr) IShopDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shopDo) Joins(fields ...field.RelationField) IShopDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shopDo) Preload(fields ...field.RelationField) IShopDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shopDo) FirstOrInit() (*domain.Shop, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Shop), nil
	}
}

func (s shopDo) FirstOrCreate() (*domain.Shop, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.Shop), nil
	}
}

func (s shopDo) FindByPage(offset int, limit int) (result []*domain.Shop, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shopDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shopDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shopDo) Delete(models ...*domain.Shop) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shopDo) withDO(do gen.Dao) *shopDo {
	s.DO = *do.(*gen.DO)
	return s
}
